export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOADING = 'LOADING';
export const LOADED = 'LOADED';


export const GET_COMPANIES = 'GET_COMPANIES';
export const COMPANIES_LOADED = 'COMPANIES_LOADED';
export const COMPANIES_FAILED = 'COMPANIES_FAILED';


export const EXPENSE_FORM_UPDATE = 'EXPENSE_FORM_UPDATE';